on :
  workflow_dispatch:

jobs:
  job_1:
    runs-on: ubuntu-latest
    steps:
      - name: Print message
        run: "echo This is job #1 with id: ${{github.job}}"

  job_2:
    runs-on: ubuntu-latest
    needs: job_1
    steps:
      - name: Print message
        run: "echo This is job #2 with id: ${{github.job}}"

  job_3:
    runs-on: ubuntu-latest
    needs: job_1
    steps:
      - name: Print message
        run: "echo This is job #3 with id: ${{github.job}}"
  
  job_4:
    runs-on: ubuntu-latest
    needs: [job_2, job_3]
    steps:
      - name: Print message
        run: "echo This is job #4 with id: ${{github.job}}"
