name: fist workflow

# trigger
on:
  push:
    branches:
      - main


# jobs:
jobs:
  example-job: # job name
    runs-on: ubuntu-latest # runs on container, OS
    steps:
      - name: Print a welcome message
        run: echo "Welcome to GitHub Actions"

      - name: Checkout repo
        uses: actions/checkout@v4.2.2

      - name: List repo files
        run: ls -la
      
