name: fist workflow

# trigger
on:
  push:
    branches:
      - main


# jobs:
jobs:
  exmaple-job: # job name
    runs-on: ubuntu-latest # runs on container , OS
    steps:
      - name: print welcome message
        run: echo "Welcome to Github Actions"
    
      
