on: 
  workflow_dispatch:
    inputs:
      environment:
        description: "Choose the environment"
        required: true
        default: "dev"
        type: choice
        options:
          - dev
          - prod
          - staging
          - test

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Print message
        run: echo "Hello World! This is a manual workflow."