on: 
  schedule:
    - cron: '0 0 * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Print message
        run: echo "Hello World! This is a schedualed workflow."
        
        